kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-data
  namespace: parasol-insurance
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem